-- auto Generated on 2018-09-15
-- DROP TABLE IF EXISTS `girl`;
CREATE TABLE `girl`(
	`id` BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '',
	`age` INT (11) NOT NULL DEFAULT -1 COMMENT '',
	`cup_size` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '',
	`money` DOUBLE (16,4) NOT NULL DEFAULT -1.0 COMMENT '',
	PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '`girl`';
